import gtk

class PinWiz(gtk.Window):
	page1,page2,page3,page4,next1,next2,next3,export=0,0,0,0,0,0,0,0

	def __init__(self):
		super(PinWiz, self).__init__()

		self.set_title("pin wiz config tool")
		self.set_size_request(320, 480)
		self.set_border_width(8)
		self.set_position(gtk.WIN_POS_CENTER)

		vbox = gtk.VBox(False, 5)
		self.page1 = gtk.VBox(False, 5)
		self.page2 = gtk.VBox(False, 5)
		self.page3 = gtk.VBox(False, 5)
		self.page4 = gtk.VBox(False, 5)

		align_bottom = gtk.Alignment(0, 1, 0, 0)
		align_top = gtk.Alignment(0, 0, 0, 0)
		
		# bottom of window  buttons
		hbox = gtk.HBox(True, 3)
		cancel = gtk.Button("cancel")
		cancel.set_size_request(70, 30)
		cancel.connect("clicked",self.quit)
		self.next1 = gtk.Button("next")
		self.next1.connect("clicked",self.cont1)
		self.next2 = gtk.Button("next")
		self.next2.connect("clicked",self.cont2)
		self.next3 = gtk.Button("next")
		self.next3.connect("clicked",self.cont3)
		self.export = gtk.Button("export")
		self.export.connect("clicked",self.cfg)
		hbox.add(cancel)
		hbox.add(self.next1)
		hbox.add(self.next2)
		hbox.add(self.next3)
		hbox.add(self.export)
		halign = gtk.Alignment(1, 0, 0, 0)
		halign.add(hbox)
		

		#checkbox buttons
		b_trackpad = gtk.CheckButton("Enable trackpad")
		b_lefthanded = gtk.CheckButton("Enable left-handed")

		#pressure curve options
		cb_label = gtk.Label("pressure curve:")
		cb_pressure = gtk.combo_box_new_text()
		cb_pressure.set_size_request(120,32)
		cb_pressure.append_text('linear')
		cb_pressure.append_text('soft')
		cb_pressure.append_text('hard')
		cb_pressure.set_active(0)


		#target offset settings
		offset_lbox = gtk.Label("monitor offset:")
		offset_box = gtk.HBox(False, 6)
		offset_x = gtk.Entry()
		offset_x.set_size_request(24,32)
		offset_x.set_text("0")
		offset_y = gtk.Entry()
		offset_y.set_text("0")
		offset_y.set_size_request(24,32)
		offset_lx = gtk.Label("x:")
		offset_ly = gtk.Label("y:")
		offset_box.add(offset_lx)
		offset_box.add(offset_x)
		offset_box.add(offset_ly)
		offset_box.add(offset_y)

		#target monitor dimensions
		dim_lbox = gtk.Label("target monitor dimensions:")
		dim_box = gtk.HBox(False, 6)
		dim_x = gtk.Entry()
		dim_x.set_text(str(gtk.gdk.screen_width()))
		dim_x.set_size_request(24,32)
		dim_y = gtk.Entry()
		dim_y.set_text(str(gtk.gdk.screen_height()))
		dim_y.set_size_request(24,32)
		dim_lx = gtk.Label("w:")
		dim_ly = gtk.Label("h:")
		dim_box.add(dim_lx)
		dim_box.add(dim_x)
		dim_box.add(dim_ly)
		dim_box.add(dim_y)


		# btn configs
		btn0 = gtk.HBox(False, 3)
		btn01 = gtk.Label("")
		btn02 = gtk.Label("mod1")
		btn02.set_size_request(16,24)
		btn03 = gtk.Label("mod2")
		btn03.set_size_request(16,24)
		btn04 = gtk.Label("key")
		btn0.add(btn01)
		btn0.add(btn02)
		btn0.add(btn03)
		btn0.add(btn04)


		# btn1
		btn1 = gtk.HBox(False, 3)
		btn11 = gtk.Label("btn1")
		btn12 = clone_widget("mod")
		btn13 = clone_widget("mod")
		btn14 = clone_widget("key")
		btn1.add(btn11)
		btn1.add(btn12)
		btn1.add(btn13)
		btn1.add(btn14)
		# btn2
		btn2 = gtk.HBox(False, 3)
		btn21 = gtk.Label("btn2")
		btn22 = clone_widget("mod")
		btn23 = clone_widget("mod")
		btn24 = clone_widget("key")
		btn2.add(btn21)
		btn2.add(btn22)
		btn2.add(btn23)
		btn2.add(btn24)
		# btn3
		btn3 = gtk.HBox(False, 3)
		btn31 = gtk.Label("btn3")
		btn32 = clone_widget("mod")
		btn33 = clone_widget("mod")
		btn34 = clone_widget("key")
		btn3.add(btn31)
		btn3.add(btn32)
		btn3.add(btn33)
		btn3.add(btn34)
		# btn4
		btn4 = gtk.HBox(False, 3)
		btn41 = gtk.Label("btn4")
		btn42 = clone_widget("mod")
		btn43 = clone_widget("mod")
		btn44 = clone_widget("key")
		btn4.add(btn41)
		btn4.add(btn42)
		btn4.add(btn43)
		btn4.add(btn44)
		# btn5
		btn5 = gtk.HBox(False, 3)
		btn51 = gtk.Label("btn5")
		btn52 = clone_widget("mod")
		btn53 = clone_widget("mod")
		btn54 = clone_widget("key")
		btn5.add(btn51)
		btn5.add(btn52)
		btn5.add(btn53)
		btn5.add(btn54)
		# btn6
		btn6 = gtk.HBox(False, 3)
		btn61 = gtk.Label("btn6")
		btn62 = clone_widget("mod")
		btn63 = clone_widget("mod")
		btn64 = clone_widget("key")
		btn6.add(btn61)
		btn6.add(btn62)
		btn6.add(btn63)
		btn6.add(btn64)

		# gesture headers
		gstr0 = gtk.HBox(False, 3)
		gstr01 = gtk.Label("")
		gstr02 = gtk.Label("mod1")
		gstr02.set_size_request(16,24)
		gstr03 = gtk.Label("mod2")
		gstr03.set_size_request(16,24)
		gstr04 = gtk.Label("key")
		gstr0.add(gstr01)
		gstr0.add(gstr02)
		gstr0.add(gstr03)
		gstr0.add(gstr04)
		# gesture1 - 2 left
		gstr1 = gtk.HBox(False, 3)
		gstr11 = gtk.Label("2 <")
		gstr12 = clone_widget("mod")
		gstr13 = clone_widget("mod")
		gstr14 = clone_widget("key")
		gstr1.add(gstr11)
		gstr1.add(gstr12)
		gstr1.add(gstr13)
		gstr1.add(gstr14)
		# gesture2 - 2 right
		gstr2 = gtk.HBox(False, 3)
		gstr21 = gtk.Label("2 >")
		gstr22 = clone_widget("mod")
		gstr23 = clone_widget("mod")
		gstr24 = clone_widget("key")
		gstr2.add(gstr21)
		gstr2.add(gstr22)
		gstr2.add(gstr23)
		gstr2.add(gstr24)
		# gesture3 - 2 up
		gstr3 = gtk.HBox(False, 3)
		gstr31 = gtk.Label("2 ^")
		gstr32 = clone_widget("mod")
		gstr33 = clone_widget("mod")
		gstr34 = clone_widget("key")
		gstr3.add(gstr31)
		gstr3.add(gstr32)
		gstr3.add(gstr33)
		gstr3.add(gstr34)
		# gesture4 - 2 down
		gstr4 = gtk.HBox(False, 3)
		gstr41 = gtk.Label("2 <")
		gstr42 = clone_widget("mod")
		gstr43 = clone_widget("mod")
		gstr44 = clone_widget("key")
		gstr4.add(gstr41)
		gstr4.add(gstr42)
		gstr4.add(gstr43)
		gstr4.add(gstr44)
		# gesture5 - 3 left
		gstr5 = gtk.HBox(False, 3)
		gstr51 = gtk.Label("3 <")
		gstr52 = clone_widget("mod")
		gstr53 = clone_widget("mod")
		gstr54 = clone_widget("key")
		gstr5.add(gstr51)
		gstr5.add(gstr52)
		gstr5.add(gstr53)
		gstr5.add(gstr54)
		# gesture6 - 3 right
		gstr6 = gtk.HBox(False, 3)
		gstr61 = gtk.Label("3 >")
		gstr62 = clone_widget("mod")
		gstr63 = clone_widget("mod")
		gstr64 = clone_widget("key")
		gstr6.add(gstr61)
		gstr6.add(gstr62)
		gstr6.add(gstr63)
		gstr6.add(gstr64)
		# gesture7 - 3 up
		gstr7 = gtk.HBox(False, 3)
		gstr71 = gtk.Label("3 ^")
		gstr72 = clone_widget("mod")
		gstr73 = clone_widget("mod")
		gstr74 = clone_widget("key")
		gstr7.add(gstr71)
		gstr7.add(gstr72)
		gstr7.add(gstr73)
		gstr7.add(gstr74)
		# gesture8 - 3 down
		gstr8 = gtk.HBox(False, 3)
		gstr81 = gtk.Label("3 v")
		gstr82 = clone_widget("mod")
		gstr83 = clone_widget("mod")
		gstr84 = clone_widget("key")
		gstr8.add(gstr81)
		gstr8.add(gstr82)
		gstr8.add(gstr83)
		gstr8.add(gstr84)


		# gesture9 - pinch in
		gstrx1 = gtk.HBox(False, 3)
		gstrx11 = gtk.Label("><")
		gstrx12 = clone_widget("mod")
		gstrx13 = clone_widget("mod")
		gstrx14 = clone_widget("key")
		gstrx1.add(gstrx11)
		gstrx1.add(gstrx12)
		gstrx1.add(gstrx13)
		gstrx1.add(gstrx14)		
		# gesture10 - pinch out
		gstrx2 = gtk.HBox(False, 3)
		gstrx21 = gtk.Label("<>")
		gstrx22 = clone_widget("mod")
		gstrx23 = clone_widget("mod")
		gstrx24 = clone_widget("key")
		gstrx2.add(gstrx21)
		gstrx2.add(gstrx22)
		gstrx2.add(gstrx23)
		gstrx2.add(gstrx24)		
		# gesture11 - tap1
		gstrx3 = gtk.HBox(False, 3)
		gstrx31 = gtk.Label("tap1")
		gstrx32 = clone_widget("mod")
		gstrx33 = clone_widget("mod")
		gstrx34 = clone_widget("key")
		gstrx3.add(gstrx31)
		gstrx3.add(gstrx32)
		gstrx3.add(gstrx33)
		gstrx3.add(gstrx34)		
		# gesture11 - tap2
		gstrx4 = gtk.HBox(False, 3)
		gstrx41 = gtk.Label("tap2")
		gstrx42 = clone_widget("mod")
		gstrx43 = clone_widget("mod")
		gstrx44 = clone_widget("key")
		gstrx4.add(gstrx41)
		gstrx4.add(gstrx42)
		gstrx4.add(gstrx43)
		gstrx4.add(gstrx44)		
		# gesture11 - tap1
		gstrx5 = gtk.HBox(False, 3)
		gstrx51 = gtk.Label("tap3")
		gstrx52 = clone_widget("mod")
		gstrx53 = clone_widget("mod")
		gstrx54 = clone_widget("key")
		gstrx5.add(gstrx51)
		gstrx5.add(gstrx52)
		gstrx5.add(gstrx53)
		gstrx5.add(gstrx54)


		#export name
		ex_box = gtk.HBox(False, 3)
		ex_l1 = gtk.Label("export as: ")
		ex_name = gtk.Entry()
		ex_name.set_text("settings.conf")
		ex_box.add(ex_l1)
		ex_box.add(ex_name)
		vbox.pack_start(align_top)


		#gtk, putting everything together
		self.page1.pack_start(b_trackpad, False, False, 3)
		self.page1.pack_start(b_lefthanded, False, False, 3)
		
		#leave fine tuning pressure adjustment to the art software
		#self.page1.pack_start(cb_label, False, False, 3)
		#self.page1.pack_start(cb_pressure, False, False, 3)
		self.page1.pack_start(offset_lbox, False, False, 3)
		self.page1.pack_start(offset_box, False, False, 3)
		self.page1.pack_start(dim_lbox, False, False, 3)
		self.page1.pack_start(dim_box, False, False, 3)
		self.page1.pack_end(ex_box, False, False, 16)


		self.page2 = gtk.VBox(False, 5)
		self.page2.pack_start(btn0, False, False, 3)
		self.page2.pack_start(btn1, False, False, 3)
		self.page2.pack_start(btn2, False, False, 3)
		self.page2.pack_start(btn3, False, False, 3)
		self.page2.pack_start(btn4, False, False, 3)
		self.page2.pack_start(btn5, False, False, 3)
		self.page2.pack_start(btn6, False, False, 3)

		self.page3 = gtk.VBox(False, 5)
		self.page3.pack_start(gstr0, False, False, 3)
		self.page3.pack_start(gstr1, False, False, 3)
		self.page3.pack_start(gstr2, False, False, 3)
		self.page3.pack_start(gstr3, False, False, 3)
		self.page3.pack_start(gstr4, False, False, 3)
		self.page3.pack_start(gstr5, False, False, 3)
		self.page3.pack_start(gstr6, False, False, 3)
		self.page3.pack_start(gstr7, False, False, 3)
		self.page3.pack_start(gstr8, False, False, 3)

		self.page4 = gtk.VBox(False, 5)
		self.page4.pack_start(gstr0, False, False, 3)
		self.page4.pack_start(gstrx1, False, False, 3)
		self.page4.pack_start(gstrx2, False, False, 3)
		self.page4.pack_start(gstrx3, False, False, 3)
		self.page4.pack_start(gstrx4, False, False, 3)
		self.page4.pack_start(gstrx5, False, False, 3)

		vbox.pack_start(self.page1, False, False, 8)
		vbox.pack_start(self.page2, False, False, 8)
		vbox.pack_start(self.page3, False, False, 8)
		vbox.pack_start(self.page4, False, False, 8)

		vbox.pack_start(align_bottom)
		vbox.pack_end(halign, False, False, 3)

		self.add(vbox)
		self.show_all()
		self.page2.hide()
		self.page3.hide()
		self.page4.hide()
		self.next2.hide()
		self.next3.hide()
		self.export.hide()

	def pressure_changed(self, widget):
		PRESSURE = widget.get_active_text()
	def quit(self,widget,data=None):
		gtk.main_quit()

	def cont1(self,widget,data=None):
		self.page1.hide()
		self.next1.hide()
		self.page2.show()
		self.next2.show()
	def cont2(self,widget,data=None):
		self.page2.hide()
		self.next2.hide()
		self.page3.show()
		self.next3.show()
	def cont3(self,widget,data=None):
		self.page3.hide()
		self.next3.hide()
		self.page4.show()
		self.export.show()

	def cfg(self,widget,data=None):
		print(self.b_trackpad.get_active())


def clone_widget(widget):
	btn_mod = gtk.combo_box_new_text()
	btn_mod.set_size_request(24,24)
	btn_mod.append_text('')
	btn_mod.append_text('ctrl')
	btn_mod.append_text('alt')
	btn_mod.append_text('shift')
	btn_mod.set_active(0)
	btn_key = gtk.combo_box_new_text()
	btn_key.append_text('')
	btn_key.append_text('e')
	btn_key.append_text('z')
	btn_key.append_text('{')
	btn_key.append_text('}')
	btn_key.append_text('up')
	btn_key.append_text('down')
	btn_key.append_text('left')
	btn_key.append_text('right')
	btn_key.append_text('+')
	btn_key.append_text('-')
	btn_key.set_active(0)
	if widget == "mod":
		return btn_mod
	if widget == "key":
		return btn_key


PinWiz()
gtk.main()